model:
    num_topic: 10
    SGLD_a:  0.5
    SGLD_b:  1000.0
    SGLD_c:  0.75
    phi_var: 1.0
    eta_var: 1.0
    alpha_var: 1.0
    seed: 3
data:
    epochs: 50
    data_dir: "data/"
    output_dir: "outputs/"


hydra:
    output_subdir: null                         # .hydra 以下ファイルの生成停止
defaults:
    - override hydra/hydra_logging: disabled  # .hydra 以下ファイルの生成停止
    - override hydra/job_logging: disabled      # ログ出力・記録停止
